# Generated by Django 4.1.6 on 2023-02-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='subject',
        ),
    ]
