# Generated by Django 4.1.6 on 2023-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_remove_document_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskdocument',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
    ]
