# Generated by Django 4.1.6 on 2023-03-17 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0002_document_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtaskdocument',
            name='field',
        ),
        migrations.RemoveField(
            model_name='subtaskdocument',
            name='title',
        ),
        migrations.AlterField(
            model_name='subtaskdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subtaskdocument',
            name='value',
            field=models.TextField(default='', max_length=50),
        ),
    ]
