# Generated by Django 4.1.6 on 2023-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_subtaskdocument_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskdocument',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
