# Generated by Django 4.1.6 on 2023-03-17 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0003_remove_subtaskdocument_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
