# Generated by Django 4.1.6 on 2023-02-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_subtaskdocument_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskdocument',
            name='student',
            field=models.CharField(default='', max_length=100),
        ),
    ]
