# Generated by Django 4.1.6 on 2023-03-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_alter_subtaskdocument_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtaskdocument',
            name='value',
            field=models.TextField(default=''),
        ),
    ]
