# Generated by Django 4.1.6 on 2023-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_subtaskdocument_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sharePermission',
            field=models.CharField(default='onlyMe', max_length=15),
        ),
    ]
