# Generated by Django 4.1.6 on 2023-03-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
