# Generated by Django 4.1.6 on 2023-03-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='customField',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='subjectId',
            field=models.CharField(default='', max_length=20),
        ),
    ]
