# Generated by Django 4.1.6 on 2023-03-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='room_id',
            new_name='classroom_id',
        ),
    ]
