# Generated by Django 4.1.6 on 2023-03-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_room_id_classroom_classroom_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classroom_id',
            new_name='room_id',
        ),
    ]
