# Generated by Django 4.1.6 on 2023-03-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_rename_classroom_id_classroom_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='session',
            field=models.CharField(default='', max_length=2),
        ),
    ]
