# Generated by Django 4.1.6 on 2023-03-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_sessions_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessions',
            name='session',
        ),
    ]
