# Generated by Django 3.2.18 on 2023-05-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_sessions_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='zoomPassword',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='zoomURl',
            field=models.TextField(default=''),
        ),
    ]
